version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
      - "5671:5671"
      - "4369:4369"
    restart: on-failure
  elasticsearch:
    image: elasticsearch:7.3.0
    container_name: elasticsearch
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    restart: on-failure
  kibana:
    image: kibana:7.3.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    restart: on-failure
  mysql: 
    image: mysql:latest
    container_name: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=photo_app
    restart: on-failure
  logstash:
    build: ./logstash
    container_name: logstash
    volumes:
      - /home/api-logs:/api-logs
    depends_on:
      elasticsearch:
        condition: service_started
      albums-ms:
        condition: service_healthy
      users-ms:
        condition: service_healthy
  config-server:
    build: ../microservices-training-local-config-server
    container_name: photoapp-config-server
    ports:
      - "8888:8888"
    environment:
      - rabbitmq.host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_started
    healthcheck:
      test: exit 0
      #test: ["CMD", "java", "HealthCheckConfigServer.java", "||", "exit", "1"]
      #interval: 5s
      #timeout: 3s
      #retries: 5
      #start_period: 15s
    restart: on-failure
  discovery-service:
    build: ./photoapp-discovery-service
    container_name: photoapp-discovery-service
    ports:
      - "8761:8761"
    environment:
      - config.host=photoapp-config-server
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: exit 0
      #test: ["CMD", "java", "HealthCheckDiscoveryService.java", "||", "exit", "1"]
      #interval: 5s
      #timeout: 3s
      #retries: 5
      #start_period: 15s
    restart: on-failure
  api-gateway:
    build: ./photoapp-api-gateway
    container_name: photoapp-api-gateway
    ports:
      - "8765:8765"
    environment:
      - eureka.host=photoapp-discovery-service
      - config.host=photoapp-config-server
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: exit 0
      #test: ["CMD", "java", "HealthCheckApiGateway.java", "||", "exit", "1"]
      #interval: 5s
      #timeout: 3s
      #retries: 5
      #start_period: 15s
    restart: on-failure
  albums-ms:
    build: ./photoapp-albums
    container_name: photoapp_albums-ms
    volumes:
      - /home/api-logs:/api-logs
    environment:
      - spring.profile=docker
      - eureka.host=photoapp-discovery-service
      - config.host=photoapp-config-server
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: exit 0
    restart: on-failure
  users-ms:
    build: ./photoapp-users
    container_name: photoapp-users-ms
    volumes:
      - /home/api-logs:/api-logs
    environment:
      - spring.profile=docker
      - eureka.host=photoapp-discovery-service
      - config.host=photoapp-config-server
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      mysql:
        condition: service_started
    healthcheck:
      test: exit 0
    restart: on-failure
volumes:
  esdata1:
    external: true