FROM openjdk:17-jdk-alpine
VOLUME /tmp
COPY target/photoapp-discovery-service-0.0.1-SNAPSHOT.jar DiscoveryService.jar
COPY health/HealthCheckDiscoveryService.java HealthCheckDiscoveryService.java
ENTRYPOINT [ "java", "-jar", "DiscoveryService.jar" ]