FROM openjdk:17-jdk-alpine
VOLUME /tmp
COPY target/photoapp-api-gateway-0.0.1-SNAPSHOT.jar ApiGateway.jar
COPY health/HealthCheckApiGateway.java HealthCheckApiGateway.java
ENTRYPOINT [ "java", "-jar", "ApiGateway.jar" ]